### ISSUE TITLE
Issue while compiling

### ISSUE THREAD

**Issue by blopblopblup** [ABeaujet/CalypsoInspector#1]
Hi, I am having trouble when I try to compile the project using javac or even maven. it's the first time I work on java project.
Could you help me ?
Best regards

**Comment by ABeaujet** [comment]
Hi,

This project was made with IntelliJ and is far from having the best architecture so compiling using javac is a bit of a pain.
I've added a Makefile and updated the README in the last 2 commits to make things simpler.

> To compile :  `$ make`
> Do not be affraid of the Makefile downloading stuff, it's just the XML lib.
> 
> To run :  `$ java -cp out/*:lib/jdom2-2.0.3.jar fr.mikado.calypsoinspector.Main`
> 
> Note for Debian-based OS users : add the following bit to the Java command line
> ` -Dsun.security.smartcardio.library=/usr/lib/x86_64-linux-gnu/libpcsclite.so.1`

Wish you good luck !
