### ISSUE TITLE
[NOT AN ISSUE] Is this code works on raspberry pi ?

### ISSUE THREAD

**Issue by m0rpheus1337** [ABeaujet/CalypsoInspector#3]
Hello,

I send this "issue" to know if the code works on a raspberry pi 3 with a RFID-RC522 plugged ?
I want to verify if my PassPass card contains some interesting information.

I notice you've test your PassPass card. If you have some tips to give me, please contact me !

Thanks :)

**Comment by ABeaujet** [comment]
Hello,

The only requirements for this code to work is a Java virtual machine implementing JRE 1.7+, a running PCSC Damon and a PCSC compatible reader.
If you plan on putting a Debian variant on your Pi, then it should work just fine (I can run it just fine under Debian 8 and current Sid).

Have fun
