### ISSUE TITLE
Remove .idea/ from repository

### ISSUE THREAD

**Issue by cvilleger** [ABeaujet/CalypsoInspector#4]
Hello (Love your project),

`.idea` is a folder specific to IntelliJ. It causes conflict with others contributors.
We need to add `.idea` directory to the list of ignored files. Then remove the directory only from the repository : 

```bash
$ echo '.idea' >> .gitignore
$ git rm -r --cached .idea
$ git add .gitignore
$ git commit -m 'untracking .idea'
$ git push origin master
```

**Comment by ABeaujet** [comment]
Hello,

I have used the .gitignore linked in this page : https://intellij-support.jetbrains.com/hc/en-us/articles/206544839-How-to-manage-projects-under-Version-Control-Systems

Can you tell me how the .idea folder is causing problems in your environment ?

**Comment by cvilleger** [comment]
I was wrong... I've never commited the idea folder, maybe this is the time, thanks !
